### ISSUE TITLE
brainstorm styling ideas with raymond

### ISSUE THREAD

**Issue by tony1542** [tony1542/RSForum#22]
What other styles / colors to add to the site / theme to make it not as bland

**Comment by KizeKaze** [comment]
Perhaps a copy right free background? maby not a picture but like a silhouette of a forest as an example.
or maby add a copy right free background picture of like tree bark/magical forest(rs theme) and make our divs more defined.

**Comment by KizeKaze** [comment]
or add one of my old school drawings of runescape as a background lol

**Comment by tony1542** [comment]
i was thinking more neutral, like maybe a darker color like the osrs website, but i'd like to stick with more flat colors for a background vs images
