### ISSUE TITLE
Create a post system

### ISSUE THREAD

**Issue by tony1542** [tony1542/RSForum#6]
Allow users to create a post.

A post should have a title & body. We don't need to worry about allowing users to comment on it right away, that can be a separate issue

**Comment by KizeKaze** [comment]
Did you mean an admin posting for the home page or any user can post something on a some page?

**Comment by tony1542** [comment]
I think any user making a post would be good to start with

**Comment by KizeKaze** [comment]
Perhaps a reddit style posting? a simple title and who it is by, but if you click on it it's like it's own little page?

**Comment by tony1542** [comment]
Sounds good to me!
